name: CI
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
  build:

  #Deklaracja Runnera z systemem operacyjnym Ubunutu:20.04
    runs-on: ubuntu-20.04
    
    steps:
      - 
        uses: actions/checkout@v3

  #Skonfigurowanie Buildx-a + Docker-a
      - 
        name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v2

  #Instalacja QEMU     
      - 
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

  #Logowanie do Github Container Registry
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{secrets.GHCR_USERNAME}}
          password: ${{secrets.GHCR_TOKEN}}

  #Logowanie do DockerHub
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DH_USER_NAME}}
          password: ${{secrets.DH_USER_TOKEN}}
  #Wersjonowanie semantyczne
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/gurum2k/fibcalc
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

  #Zbudowanie obrazu i wypchanie obrazu
      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=docker.io/patryg/fibcalc:cache
          cache-to: type=registry,ref=docker.io/patryg/fibcalc:cache
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          file: Dockerfile
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}